# Generated by Django 5.2.17 on 2026-10-02 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hero_heading', models.CharField(blank=True, max_length=160)),
                ('hero_subheading', models.CharField(blank=True, max_length=240)),
                ('hero_image', models.ImageField(blank=True, upload_to='site/')),
                ('cta_label', models.CharField(blank=True, default='Explore the menu', max_length=40)),
                ('is_active', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='foodcategory',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='fooditem',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
    ]
