# Generated by Django 5.2.17 on 2026-10-02 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0002_sitecontent_foodcategory_is_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fooditem',
            name='is_popular',
            field=models.BooleanField(default=False),
        ),
    ]
